state_dbfile = "igor.sqlite"

[channels]

[channels.discord]
class = "Discord"
[channels.console]
class = "Console"
[channels.telegram]
class = "Telegram"

[reactors]

[reactors.fortune]
class = "Fortune"
[reactors.echoreactor]
class = "EchoReactor"
[reactors.catpic]
class = "CatPic"
[reactors.sentiment]
class = "SentimentReactor"
