state_dbfile = "igor.sqlite"

[channels]

[channels.discord]
class = "Discord"
[channels.console]
class = "Console"

[reactors]

[reactors.fortune]
class = "Fortune"
[reactors.echoreactor]
class = "EchoReactor"
